### ISSUE TITLE
Custom theme with spring boot failes to persist cache

### ISSUE THREAD

**Issue by eiswind** [vaadin/spring#13]
I currently see that - when I try to use my own theme -, that this tries to go to a folder that does not exist in my filesystem. Do you have any idea how I can solve this?

WARNUNG: Error persisting scss cache /tmp/tomcat-docbase.7952762783312185530.8080/VAADIN/themes/mytheme/styles.scss.cache
java.io.FileNotFoundException: /tmp/tomcat-docbase.7952762783312185530.8080/VAADIN/themes/mytheme/styles.scss.cache (Datei oder Verzeichnis nicht gefunden)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at com.google.gwt.thirdparty.guava.common.io.Files$FileByteSink.openStream(Files.java:201)
	at com.google.gwt.thirdparty.guava.common.io.Files$FileByteSink.openStream(Files.java:189)
	at com.google.gwt.thirdparty.guava.common.io.ByteSink$AsCharSink.openStream(ByteSink.java:163)
	at com.google.gwt.thirdparty.guava.common.io.CharSink.write(CharSink.java:110)
	at com.google.gwt.thirdparty.guava.common.io.Files.write(Files.java:477)
	at com.vaadin.server.VaadinServlet.persistCacheEntry(VaadinServlet.java:1304)
	at com.vaadin.server.VaadinServlet.serveOnTheFlyCompiledScss(VaadinServlet.java:966)
	at com.vaadin.server.VaadinServlet.serveStaticResourcesInVAADIN(VaadinServlet.java:734)
	at com.vaadin.server.VaadinServlet.serveStaticResources(VaadinServlet.java:699)

**Comment by lightoze** [comment]
I second this issue. Adding `cacheFile.getParentFile().mkdirs()` immediately before `Files.write` call should help.

**Comment by samie** [comment]
Created a ticket in Vaadin for this: https://dev.vaadin.com/ticket/18463

**Comment by hesara** [comment]
Tracked in Vaadin Trac.

**Comment by BruceRodrigues** [comment]
The VaadinServlet looks only in his own project for the .scss files. If your theme is in a different project try to move it to the same one.

**Comment by casamanya** [comment]
I've had the same issue and creating a putting the theme inside src/main/webapp/VAADIN folder worked for me. 

http://www.sothawo.com/2015/06/custom-theme-for-a-vaadin-spring-boot-application/

**Comment by lightoze** [comment]
@casamanya another way to get rid of the error (without having to edit pom.xml) is to add this to your application:
```java
    @Autowired
    private ServletContext servletContext;

    @PostConstruct
    public void init() throws IOException {
        String root = servletContext.getRealPath("/");
        if (root != null && Files.isDirectory(Paths.get(root))) {
            // workaround for https://dev.vaadin.com/ticket/18463
            Files.createDirectories(Paths.get(servletContext.getRealPath("/VAADIN/themes/mytheme")));
        }
    }
```

**Comment by mvrueden** [comment]
@lightoze thank you for your workaround.
I modified the example a bit, to make it more generic:
 
    @PostConstruct
    public void init() throws IOException {
        Theme annotation = getUI().getClass().getAnnotation(Theme.class);
        if (annotation != null) {
            String root = servletContext.getRealPath("/");
            if (root != null && Files.isDirectory(Paths.get(root))) {
                Files.createDirectories(Paths.get(servletContext.getRealPath("/VAADIN/themes/" + annotation.value())));
            }
        }
    }
