### ISSUE TITLE
SpringUIProvider.createInstance sets the CurrentInstace of UIID null

### ISSUE THREAD

**Issue by peterl1084** [vaadin/spring#174]
Why does SpringUIProvider.createInstance sets the CurrentInstace of UIID null in the end? This causes Assertation error later in 

`java.lang.IllegalArgumentException: Found no valid com.vaadin.spring.internal.UIID instance!
	at org.springframework.util.Assert.notNull(Assert.java:115) ~[spring-core-4.3.5.RELEASE.jar:4.3.5.RELEASE]
	at com.vaadin.spring.internal.UIScopeImpl$VaadinSessionBeanStoreRetrievalStrategy.getUIID(UIScopeImpl.java:158) ~[vaadin-spring-2.0.0.beta1.jar:2.0.0.beta1]
	at com.vaadin.spring.internal.UIScopeImpl$VaadinSessionBeanStoreRetrievalStrategy.getBeanStore(UIScopeImpl.java:168) ~[vaadin-spring-2.0.0.beta1.jar:2.0.0.beta1]`

**Comment by peterl1084** [comment]
This means that when beans are created with UI they work for the first time, but if user refreshes the browser as then UI.getCurrent is returning null at the time of bean creation it reverts back to trying UIID, but as that's been set to null in browserDetails request it also fails causing the assertation error appear (correctly).

**Comment by peterl1084** [comment]
The problem cannot be fixed as proposed as moving the setting current UI higher simply doesn't work as UI is not yet initialized at that stage.

Also, the above described problem only occurs when the bean is in proxied mode (with TARGET_CLASS). Otherwise the first description is still accurate.

**Comment by vaadin-miki** [comment]
this happens also when using [karibu testing for v8](https://github.com/mvysny/karibu-testing/tree/master/karibu-testing-v8) when the main UI class is a UI-scoped bean; fetching it from `ApplicationContext` to pass to `MockVaadin.setup()` raises exactly the same error message

not that it matters ;)
