### ISSUE TITLE
Vaadin breaks spring-boot-devtools reloads

### ISSUE THREAD

**Issue by mtrojahn** [vaadin/spring#179]
I'm reproducing the same question I did on StackOverflow (http://stackoverflow.com/questions/42023529/vaadin-breaks-spring-boot-devtools-reload):

I'm trying out Vaadin for a few days now and the most annoying thing is that spring-boot-devtools always fails to properly reload my project since I added Vaadin to it and created a simple View. (it is originally a Thymeleaf MVC project)

If I remove Vaadin and comment out the classes I've created, everything is back to normal. Not being able to reload is quite annoying since the project is very dependent of Spring Security.

This is what I get when I recompile the project, causing devtools to reload:

```
2017-02-03 09:30:14.034 DEBUG 10528 --- [Thread-7] o.s.b.f.support.DisposableBeanAdapter    : Invoking destroy() on bean with name 'requestContextFilter'
2017-02-03 09:30:14.034 DEBUG 10528 --- [Thread-7] o.s.b.f.s.DefaultListableBeanFactory     : Retrieved dependent beans for bean 'objectPostProcessor': [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration, org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration, authenticationManagerBuilder, org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration, h2ConsoleSecurityConfigurer]
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.s.DefaultListableBeanFactory     : Retrieved dependent beans for bean 'org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration': [h2ConsoleSecurityConfigurer, authenticationManager]
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.support.DisposableBeanAdapter    : Invoking destroy() on bean with name 'objectPostProcessor'
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.s.DefaultListableBeanFactory     : Retrieved dependent beans for bean 'validator': [methodValidationPostProcessor]
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.support.DisposableBeanAdapter    : Invoking destroy() on bean with name 'validator'
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.support.DisposableBeanAdapter    : Invoking destroy() on bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor'
2017-02-03 09:30:14.049 DEBUG 10528 --- [Thread-7] o.s.b.f.s.DefaultListableBeanFactory     : Retrieved dependent beans for bean 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory': [org.springframework.context.annotation.internalConfigurationAnnotationProcessor]
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] c.v.spring.internal.UIScopeImpl$UIStore  : Vaadin service has been destroyed, destroying [UIStore[id=230d8019, sessionId=8C47AB9C565C8E7D8BF706C1F2C84801]]
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] com.vaadin.spring.internal.BeanStore     : Destroying [UIBeanStore[id=61ef3d51, name=UI:0]]
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] .s.c.a.CommonAnnotationBeanPostProcessor : Invoking destroy method on bean 'viewCache': void com.vaadin.spring.internal.DefaultViewCache.destroy()
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] com.vaadin.spring.internal.BeanStore     : Destroying [ViewBeanStore[id=50572723, name=null:]]
2017-02-03 09:30:14.143  WARN 10528 --- [localhost-startStop-2] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'viewCache'

2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] c.v.spring.internal.UIScopeImpl$UIStore  : Vaadin service has been destroyed, destroying [UIStore[id=230d8019, sessionId=8C47AB9C565C8E7D8BF706C1F2C84801]]
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] com.vaadin.spring.internal.BeanStore     : Destroying [UIBeanStore[id=61ef3d51, name=UI:0]]
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] .s.c.a.CommonAnnotationBeanPostProcessor : Invoking destroy method on bean 'viewCache': void com.vaadin.spring.internal.DefaultViewCache.destroy()
2017-02-03 09:30:14.143 DEBUG 10528 --- [localhost-startStop-2] com.vaadin.spring.internal.BeanStore     : Destroying [ViewBeanStore[id=50572723, name=null:]]
2017-02-03 09:30:14.143  WARN 10528 --- [localhost-startStop-2] .s.c.a.CommonAnnotationBeanPostProcessor : Invocation of destroy method failed on bean with name 'viewCache'

java.lang.NullPointerException: null
    at com.vaadin.spring.internal.DefaultViewCache.destroy(DefaultViewCache.java:196) ~[vaadin-spring-1.2.0.jar:1.2.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:325) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:154) ~[spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253) [spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at org.springframework.beans.factory.support.DisposableBeanAdapter.run(DisposableBeanAdapter.java:246) [spring-beans-4.3.6.RELEASE.jar:4.3.6.RELEASE]
    at com.vaadin.spring.internal.BeanStore.destroy(BeanStore.java:101) [vaadin-spring-1.2.0.jar:1.2.0]
    at com.vaadin.spring.internal.SessionLockingBeanStore.destroy(SessionLockingBeanStore.java:66) [vaadin-spring-1.2.0.jar:1.2.0]
    at com.vaadin.spring.internal.UIScopeImpl$UIStore.destroy(UIScopeImpl.java:237) [vaadin-spring-1.2.0.jar:1.2.0]
    at com.vaadin.spring.internal.UIScopeImpl$UIStore.serviceDestroy(UIScopeImpl.java:247) [vaadin-spring-1.2.0.jar:1.2.0]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508) [vaadin-server-7.6.8.jar:7.6.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198) [vaadin-server-7.6.8.jar:7.6.8]
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161) [vaadin-server-7.6.8.jar:7.6.8]
    at com.vaadin.server.VaadinService.destroy(VaadinService.java:1893) [vaadin-server-7.6.8.jar:7.6.8]
    at com.vaadin.server.VaadinServlet.destroy(VaadinServlet.java:1360) [vaadin-server-7.6.8.jar:7.6.8]
    at org.apache.catalina.core.StandardWrapper.unload(StandardWrapper.java:1340) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.core.StandardWrapper.stopInternal(StandardWrapper.java:1671) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5399) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1435) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424) [tomcat-embed-core-8.5.11.jar:8.5.11]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]

2017-02-03 09:30:14.721 DEBUG 10528 --- [Thread-7] o.s.boot.devtools.restart.Restarter      : Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@445380be
2017-02-03 09:30:14.721 DEBUG 10528 --- [Thread-7] o.s.boot.devtools.restart.Restarter      : Starting application com.marcelustrojahn.agile.configuration.Application with URLs [file:/E:/Development/marcelustrojahn/agile-crm/target/    classes/]
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] .b.l.ClasspathLoggingApplicationListener : Application started with classpath: [file:/E:/Development/marcelustrojahn/agile-crm/target/classes/]
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'context.listener.classes' in any property source
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'banner.image.location' in any property source
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'banner.location' in any property source
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.w.c.s.StandardServletEnvironment     : Adding [servletConfigInitParams] PropertySource with lowest search precedence
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.w.c.s.StandardServletEnvironment     : Adding [servletContextInitParams] PropertySource with lowest search precedence
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.w.c.s.StandardServletEnvironment     : Adding [systemProperties] PropertySource with lowest search precedence
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.w.c.s.StandardServletEnvironment     : Adding [systemEnvironment] PropertySource with lowest search precedence
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.w.c.s.StandardServletEnvironment     : Initialized StandardServletEnvironment with PropertySources [    servletConfigInitParams,servletContextInitParams,systemProperties,systemEnvironment]
2017-02-03 09:30:14.877 DEBUG 10528 --- [restartedMain] o.s.c.a.ClassPathBeanDefinitionScanner   : JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'context.initializer.classes' in any property source
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.config.name:application' in any property source
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.config.name' in any property source
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'vcap.application.name:application' in any property source
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'vcap.application.name' in any property source
2017-02-03 09:30:14.893 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.application.name:application' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.application.name' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'PORT:null' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'PORT' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'server.port:null' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'server.port' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.application.index:null' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'spring.application.index' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'vcap.application.instance_index:null' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.c.e.PropertySourcesPropertyResolver  : Could not find key 'vcap.application.instance_index' in any property source
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Registering scope 'restart' with implementation [org.springframework.boot.devtools.restart.RestartScopeInitializer$RestartScope@9929720]
2017-02-03 09:30:14.909 DEBUG 10528 --- [restartedMain] o.s.b.f.s.DefaultListableBeanFactory     : Returning cached instance of singleton bean 'autoConfigurationReport'
2017-02-03 09:30:14.909  INFO 10528 --- [restartedMain] c.m.agile.configuration.Application      : Starting Application on DESKTOP-P5AO315 with PID 10528
```

**Comment by Artur-** [comment]
Do you have an example (project) which does not work? I'm using spring-boot-devtools in my current project and have not seen this problem

**Comment by mhosio** [comment]
In my case switching from Navigator to SpringNavigator fixed the problem
