### ISSUE TITLE
Multi-module Spring Boot 2.0 Vaadin app missing Sass compiler dependencies

### ISSUE THREAD

**Issue by danmattsson** [vaadin/spring#188]
I've set up a multi-module Spring Boot 2.0.0-SNAPSHOT app with Vaadin 8.0 RC where the root module is practically empty, see below. When running this, it causes notification of a few dependencies such as:

```
2017-02-20 11:25:36.450  WARN 87003 --- [ost-startStop-1] o.a.tomcat.util.scan.StandardJarScanner  : Failed to scan [file:/Users/dan/.m2/repository/com/vaadin/vaadin-sass-compiler/0.9.13/sac-1.3.jar] from classloader hierarchy

java.io.FileNotFoundException: /Users/dan/.m2/repository/com/vaadin/vaadin-sass-compiler/0.9.13/sac-1.3.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_102]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_102]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_102]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_102]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_102]
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:48) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:338) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:288) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262) [tomcat-embed-jasper-8.5.11.jar:8.5.11]
	at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:104) [tomcat-embed-jasper-8.5.11.jar:8.5.11]
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:101) [tomcat-embed-jasper-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5178) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

The others are:
```
java.io.FileNotFoundException: /Users/dan/.m2/repository/com/vaadin/vaadin-sass-compiler/0.9.13/flute-1.3.0.gg2.jar
java.io.FileNotFoundException: /Users/dan/.m2/repository/com/vaadin/vaadin-sass-compiler/0.9.13/yuicompressor-2.4.8.jar (No such file or directory)
java.io.FileNotFoundException: /Users/dan/.m2/repository/com/vaadin/vaadin-sass-compiler/0.9.13/js-1.7R2.jar (No such file or directory)
```

I'm using IntelliJ IDEA 2016.3 and start the project using the Spring Boot runner.

Apart from that it seems to work well. My Maven conf is:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.domain</groupId>
    <artifactId>project</artifactId>
    <version>2.0-SNAPSHOT</version>

    <packaging>pom</packaging>
    <modules>
        <module>web</module>
    </modules>

    <parent>
      <groupId>org.springframework.boot</groupId>
  		<artifactId>spring-boot-starter-parent</artifactId>
  		<version>2.0.0.BUILD-SNAPSHOT</version>
  		<relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
		<!-- The main class to start by executing java -jar -->
		<start-class>com.domain.project.web.WebApplication</start-class>
    </properties>

    <repositories>
  		<repository>
  			<id>spring-snapshots</id>
  			<name>Spring Snapshots</name>
  			<url>https://repo.spring.io/snapshot</url>
  			<snapshots>
  				<enabled>true</enabled>
  			</snapshots>
  		</repository>
  		<repository>
  			<id>spring-milestones</id>
  			<name>Spring Milestones</name>
  			<url>https://repo.spring.io/milestone</url>
  			<snapshots>
  				<enabled>false</enabled>
  			</snapshots>
  		</repository>
  		<repository>
  			<id>vaadin-prereleases</id>
  			<name>Vaadin Prereleases</name>
  			<url>https://maven.vaadin.com/vaadin-prereleases/</url>
  			<snapshots>
  				<enabled>false</enabled>
  			</snapshots>
  		</repository>
  	</repositories>
    
  	<pluginRepositories>
  		<pluginRepository>
  			<id>spring-snapshots</id>
  			<name>Spring Snapshots</name>
  			<url>https://repo.spring.io/snapshot</url>
  			<snapshots>
  				<enabled>true</enabled>
  			</snapshots>
  		</pluginRepository>
  		<pluginRepository>
  			<id>spring-milestones</id>
  			<name>Spring Milestones</name>
  			<url>https://repo.spring.io/milestone</url>
  			<snapshots>
  				<enabled>false</enabled>
  			</snapshots>
  		</pluginRepository>
  	</pluginRepositories>
</project>
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.domain.project</groupId>
	<artifactId>subproject</artifactId>
	<version>2.0-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>Web Project</name>
	<description>Web component for Project</description>

	<parent>
		<groupId>com.domain</groupId>
		<artifactId>project</artifactId>
		<version>2.0-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<!--<dependency>-->
			<!--<groupId>org.apache.tomcat.embed</groupId>-->
			<!--<artifactId>tomcat-embed-jasper</artifactId>-->
			<!--&lt;!&ndash;<scope>provided</scope>&ndash;&gt;-->
		<!--</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-actuator-docs</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
		</dependency>
		<!--dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-social-facebook</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-social-linkedin</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-social-twitter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.vaadin</groupId>
			<artifactId>vaadin-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>8.0.0.rc1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by danmattsson** [comment]
Oh - I'm using IntelliJ IDEA 2016.3 and start the project using the Spring Boot runner.

**Comment by elmot** [comment]
Spring-boot 2 is under development, and vaadin-spring 2.0.0 supports only Spring Boot 1.4 and 1.5.

Sorry, we do not support spring-boot 2 for the moment.

**Comment by elmot** [comment]
See #190

**Comment by tsuoanttila** [comment]
Unable to reproduce. I created a multimodule project from a test project I did last friday, and I don't seem to be able to get the error notifications you get. I had some issues running the pom.xml files you provided so could not test it out of the box. If you can put the project into github/bitbucket/somewhere else so that we can test it directly, then I can't help on that.

The one thing that catches my eye is the location it is looking for the sac-1.3.jar which is under the vaadin-sass-compiler, not org/w3c/css/sac . 

My testing setup was Eclipse Neon (JavaEE edition), tested both running the application as java program as well as using command line `mvn spring-boot:run`. The tested multimodule project can be found [here](https://github.com/tsuoanttila/cologne-jug/tree/multimodule)

**Comment by snicoll** [comment]
@elmot I understand you don't but that's an option served from start.spring.io after I asked @mstahv - IMO, it would be beneficial to take those reports into account for a matter of forward compatibility at least. If Spring or Spring Boot goes in your way, it will be on us and I am more than happy to assist you.

**Comment by elmot** [comment]
@danmattsson, this issue does not look like an issue of vaadin-spring but some problems with project dependencies setup.
I opened another ticket (#190) to make a comprehensive example of vaadin 8 + spring-boot 2.

Thank you to tipping us that multi-module configuration might be problematic.

**Comment by mstahv** [comment]
Yes, we should definitely look into what is going on, even though it is not "officially supported yet". I hope we don't close tickets based on this kind of thinking ;-)

**Comment by danmattsson** [comment]
Thanks, @elmot and @tsuoanttila - I cloned the repo, changed it into a multi-module project and ran it without any issue in IntelliJ, using both the Spring Boot runner and `mvn spring-boot:run`. I've tried to make my own project mimic the cologne-jug structure but I stil get the same errors. Obviously there's got to be something seriously wrong with my Maven/POMs - sorry for the wild goose chase.
