### ISSUE TITLE
VaadinSession is not open for every second visit after enable push

### ISSUE THREAD

**Issue by zxyroy** [vaadin/spring#207]
I try to reproduce the situation in a new clean project but failed. So I can only description the problem I faced.

I use spring boot 1.5.2 with Vaadin 8.0.5

This problem happens every 2\4\6 times I visit it. It is failed to create SpringUI bean after enable push. It said it cause since Current VaadinSession is not open

Here is the full stacktrace:
```
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [com.vaadin.server.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testUI': Scope 'vaadin-ui' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Current VaadinSession is not open] with root cause

java.lang.IllegalStateException: Current VaadinSession is not open
	at com.vaadin.spring.internal.UIScopeImpl$VaadinSessionBeanStoreRetrievalStrategy.getVaadinSession(UIScopeImpl.java:148) ~[vaadin-spring-2.0.1.jar:2.0.1]
	at com.vaadin.spring.internal.UIScopeImpl$VaadinSessionBeanStoreRetrievalStrategy.getUIStore(UIScopeImpl.java:155) ~[vaadin-spring-2.0.1.jar:2.0.1]
	at com.vaadin.spring.internal.UIScopeImpl$VaadinSessionBeanStoreRetrievalStrategy.getBeanStore(UIScopeImpl.java:184) ~[vaadin-spring-2.0.1.jar:2.0.1]
	at com.vaadin.spring.internal.UIScopeImpl.getBeanStore(UIScopeImpl.java:103) ~[vaadin-spring-2.0.1.jar:2.0.1]
	at com.vaadin.spring.internal.UIScopeImpl.get(UIScopeImpl.java:79) ~[vaadin-spring-2.0.1.jar:2.0.1]
```

**Comment by aspan** [comment]
I ran into the same issue and what I did was to change to `ChangeSessionIdAuthenticationStrategy`.
You need to be running your app in a servlet 3.1+ environment to use `ChangeSessionIdAuthenticationStrategy` which uses the servlet containers built in support for changing the session ID. I'm running spring boot with undertow and it works as expected. I haven't tested tomcat or jetty though.

**Comment by khauser** [comment]
It works also for tomcat:
```
    /**
     * The {@link SessionAuthenticationStrategy} must be available as a Spring
     * bean for Vaadin4Spring.
     */
    @Bean
    public SessionAuthenticationStrategy sessionAuthenticationStrategy()
    {
        return new ChangeSessionIdAuthenticationStrategy();
    }
```
