### ISSUE TITLE
Spring boot test fails

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/spring#295]
`CoExistingSpringEndpointsIT.assertRoutesAndSpringEndpoint` test fails.
It's caused by:

(`RootNavigationTarget`  is not instantiated )

```
Caused by: java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:521) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:535) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:380) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.StateTree.markAsDirty(StateTree.java:248) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.StateNode.markAsDirty(StateNode.java:325) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.nodefeature.NodeList.addChange(NodeList.java:276) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.nodefeature.NodeList.clear(NodeList.java:400) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.clear(StateNodeNodeList.java:76) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.clear(ElementChildrenList.java:56) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeAllChildren(AbstractNodeStateProvider.java:104) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.dom.Node.removeAllChildren(Node.java:359) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.dom.Element.setTextContent(Element.java:986) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.dom.Element.setText(Element.java:972) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.component.HasText.setText(HasText.java:41) ~[flow-server-1.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at com.vaadin.flow.spring.test.RootNavigationTarget.<init>(RootNavigationTarget.java:36) ~[vaadin-test-spring-common-10.0-SNAPSHOT.jar:na]
[13:13:59] :	 [Step 3/4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_161]
[13:13:59] :	 [Step 3/4] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_161]
[13:13:59] :	 [Step 3/4] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_161]
[13:13:59] :	 [Step 3/4] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_161]
[13:13:59] :	 [Step 3/4] 	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) 
```

**Comment by denis-anisimov** [comment]
Test fails remotely on the tests hub.
Doesn't fail locally.
