### ISSUE TITLE
Cannot upload files with Upload component in WildFly 12

### ISSUE THREAD

**Issue by heruan** [vaadin/spring#299]
Uploading files with Vaadin's `Upload` component in a Spring app deployed in WildFly 12 throws an error:

```
Caused by: java.lang.IllegalStateException: UT010057: multipart config was not present on Servlet
	at io.undertow.servlet.spec.HttpServletRequestImpl.verifyMultipartServlet(HttpServletRequestImpl.java:523)
	at io.undertow.servlet.spec.HttpServletRequestImpl.getParts(HttpServletRequestImpl.java:512)
	at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:390)
	at org.springframework.web.multipart.support.StandardMultipartHttpServletRequest.parseRequest(StandardMultipartHttpServletRequest.java:93)
	... 95 more
```

Seems like something is disabled on the servlet config.

**Comment by heruan** [comment]
Any update on this? I'm still not able to upload files with Vaadin + Spring in WildFly (Undertow).

**Comment by Legioth** [comment]
Potentially related to https://github.com/vaadin/vaadin-upload-flow/issues/59?

**Comment by denis-anisimov** [comment]
The original ticket is the normal Spring behavior.
I've created a ticket for documentation: 
https://github.com/vaadin/flow-and-components-documentation/issues/240

You have mentioned another bug. Please extract it from here.
It should be totally separate issue because it doesn't relate to the reported exception which has a different cause.

I'm closing this ticket.
