### ISSUE TITLE
Project cannot be built

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#304]
Running `mvn clean install` results in

```
2018-05-16 09:20:58.915  WARN 36872 --- [tializer.main()] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
2018-05-16 09:20:58.922  INFO 36872 --- [tializer.main()] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-05-16 09:20:58.928 ERROR 36872 --- [tializer.main()] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.vaadin.flow.spring.scan.test.TestServletInitializer.main(TestServletInitializer.java:40) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
```

```
[INFO] Reactor Summary:
[INFO] 
[INFO] vaadin-spring-parent 10.0-SNAPSHOT ................. SUCCESS [  0.493 s]
[INFO] vaadin-spring ...................................... SUCCESS [  7.228 s]
[INFO] Spring Boot Starter ................................ SUCCESS [  0.074 s]
[INFO] Vaadin Spring tests ................................ SUCCESS [  0.445 s]
[INFO] Flow Spring Common UI components ................... SUCCESS [  0.906 s]
[INFO] Vaadin Spring Boot integration tests ............... SUCCESS [ 17.070 s]
[INFO] Vaadin Spring Boot integration tests with custom packages to scan FAILURE [ 30.369 s]
[INFO] Vaadin Spring Boot deployable integration tests .... SKIPPED
[INFO] Flow Spring deployable integration tests 10.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by elmot** [comment]
What the branch?

**Comment by Artur-** [comment]
master

**Comment by ZheSun88** [comment]
Cannot reproduce the issue

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] vaadin-spring-parent 10.0-SNAPSHOT ................. SUCCESS [  0.594 s]
[INFO] vaadin-spring ...................................... SUCCESS [ 13.331 s]
[INFO] Spring Boot Starter ................................ SUCCESS [  0.150 s]
[INFO] Vaadin Spring tests ................................ SUCCESS [  2.593 s]
[INFO] Flow Spring Common UI components ................... SUCCESS [  2.420 s]
[INFO] Vaadin Spring Boot integration tests ............... SUCCESS [ 39.346 s]
[INFO] Vaadin Spring Boot integration tests with custom packages to scan SUCCESS [ 35.804 s]
[INFO] Vaadin Spring Boot deployable integration tests .... SUCCESS [ 31.813 s]
[INFO] Flow Spring deployable integration tests 10.0-SNAPSHOT SUCCESS [ 26.601 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:33 min
[INFO] Finished at: 2018-05-16T14:55:36+03:00
```

**Comment by Artur-** [comment]
Apparently caused by broken Jetty jars in the local `.m2` cache
