### ISSUE TITLE
IllegalStateException: Can't move a node from one state tree to another

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#308]
If you run `mvn spring-boot:run` in `vaadin-spring-tests/test-spring-boot`, open http://localhost:8888/foo and then refresh, you get

```
java.lang.IllegalStateException: Can't move a node from one state tree to another
        at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:492) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.StateNode.lambda$setTree$2(StateNode.java:265) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:451) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:265) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:197) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:77) ~[flow-server-1.0-SNAPSHOT.jar:na]
        at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:52) ~[flow-server-1.0-SNAPSHOT.jar:na]
```

**Comment by denis-anisimov** [comment]
Sorry for confusion but this is kind of by design.
The code is written "incorrectly" because it uses singleton view (it's intended to be used ONLY in one UI).
And this is expected exception.
Because this is just a test :)

May be fixed of course but the test logic have to be changed dramatically .
Is it really an issue?

**Comment by rkalau5296** [comment]
This happend when I tried to reload the page. I read somewhere about @PreserveOnRefresh. I added it to my main gui class, and problem stopped to persist:


@Route("")
@PreserveOnRefresh
public class AppLayoutWithNavbarMenu extends AppLayout {
}
