### ISSUE TITLE
Vaadin 7 - NoSuchMethodError: org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeServices

### ISSUE THREAD

**Issue by Artgit** [vaadin/spring#31]
I can't run my Spring Boot/Vaadin application on Standalone Tomcat 8.0.35 with a following exception:

```
java.lang.NoSuchMethodError: org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeServices()Lorg/springframework/security/web/authentication/RememberMeServices;
    at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeParameter(DefaultVaadinSharedSecurity.java:101)
    at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.login(DefaultVaadinSharedSecurity.java:65)
    at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.login(DefaultVaadinSharedSecurity.java:164)
```

The same application perfectly runs on Embedded Tomcat.

This is my Security configuration:

```
@Configuration
@EnableWebSecurity
@EnableVaadinSharedSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private SocialAuthenticationSuccessHandler socialAuthenticationSuccessHandler;

    @Autowired
    private DBUserDetailsService userDetailsService;

    @Value("${social.postLogin.url}")
    private String postLoginUrl;

    @Override
    public void configure(WebSecurity web) throws Exception {
        // @formatter:off
        web.ignoring()
            .antMatchers("/static/**")
            .antMatchers("/VAADIN/**");
        // @formatter:on
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        // @formatter:off

        // Set a custom successHandler on the SocialAuthenticationFilter
        final SpringSocialConfigurer socialConfigurer = new SpringSocialConfigurer();
        socialConfigurer.addObjectPostProcessor(new ObjectPostProcessor<SocialAuthenticationFilter>() {
            @Override
            public <O extends SocialAuthenticationFilter> O postProcess(O socialAuthenticationFilter) {
                socialAuthenticationFilter.setAuthenticationSuccessHandler(socialAuthenticationSuccessHandler);
                socialAuthenticationFilter.setPostLoginUrl(postLoginUrl);
                return socialAuthenticationFilter;
            }
        });

        http
            .csrf().disable() // Use Vaadin's built-in CSRF protection instead
            .sessionManagement().sessionAuthenticationStrategy(sessionAuthenticationStrategy())
        .and()
            .httpBasic().disable()
            .formLogin().disable()
            .rememberMe().rememberMeServices(rememberMeServices()).key("myAppKey")
        .and()
            .logout()
                .addLogoutHandler(new VaadinSessionClosingLogoutHandler()).logoutUrl("/logout")
                .logoutSuccessUrl("/login?logout").permitAll()
        .and()
            .exceptionHandling().authenticationEntryPoint(new LoginUrlAuthenticationEntryPoint("/login"))
        //Configures url based authorization
        .and()
            .authorizeRequests()
                //Anyone can access the urls
                .antMatchers("/login/**").anonymous()
                .antMatchers("/vaadinServlet/UIDL/**").permitAll()
                .antMatchers("/vaadinServlet/HEARTBEAT/**").permitAll()
                .antMatchers("/auth/**").permitAll()
                .antMatchers("/actuator/health").permitAll()
                .antMatchers("/actuator/**").hasAuthority("PERMISSION_READ_ACTUATOR_DATA")
                //.anyRequest().authenticated()
        //Adds the SocialAuthenticationFilter to Spring Security's filter chain.
        .and()
            // apply the configuration from the socialConfigurer (adds the SocialAuthenticationFilter)
            .apply(socialConfigurer);

        // @formatter:on
    }

    /**
     * The {@link RememberMeServices} must be available as a Spring bean for
     * Vaadin4Spring.
     */
    @Bean
    public RememberMeServices rememberMeServices() {
        return new TokenBasedRememberMeServices("myAppKey", userDetailsService);
    }

    @Bean
    public SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new SessionFixationProtectionStrategy();
    }

    @Bean(name = VaadinSharedSecurityConfiguration.VAADIN_AUTHENTICATION_SUCCESS_HANDLER_BEAN)
    VaadinAuthenticationSuccessHandler vaadinAuthenticationSuccessHandler(HttpService httpService, VaadinRedirectStrategy vaadinRedirectStrategy) {
        return new VaadinUrlAuthenticationSuccessHandler(httpService, vaadinRedirectStrategy, "/");
    }

    /**
     * Configures the authentication manager bean which processes authentication
     * requests.
     */
    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.userDetailsService(userDetailsService).passwordEncoder(new BCryptPasswordEncoder());
    }

    @Override
    @Bean
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

}
```

In my war file I have `vaadin-spring-ext-security-0.0.7.RELEASE.jar` 

What can be wrong and how to solve this issue ?

**Comment by peholmst** [comment]
This looks like a Vaadin4Spring issue, not a Vaadin Spring issue. Please report the issue here: https://github.com/peholmst/vaadin4spring

**Comment by Artgit** [comment]
Added issue, thanks https://github.com/peholmst/vaadin4spring/issues/283
