### ISSUE TITLE
support for spring-session

### ISSUE THREAD

**Issue by Firestorm87** [vaadin/spring#340]
I would like to deploy my vaadin-flow application in an kubernetes cluster with stateless vaadin pods.
The http session should be stored in a redis-cluster via spring-session-data-redis.

If i add spring-session jdbc or redis to my vaadin-spring-boot-application the application is very slow and does a full page reload after a few seconds. Everything else looks like it is working normally.

There are no warnings or exception in frontend or backend.

How to reproduce:
add 
     spring-session-core
     spring-session-data-redis

to pom of spring-boot-vaadin-app (e.g. bakery-app).

add

spring.session.store-type=redis
spring.redis.host=localhost
spring.redis.port=6379`

to application.properties

**Comment by Artur-** [comment]
The problems with Redis has previously been discussed in https://github.com/vaadin/framework/pull/9189

**Comment by Firestorm87** [comment]
ok. it means spring session, or replicated sessions at all are generally not supported?

**Comment by Zacherl** [comment]
I have another issue with Spring, Vaadin and shared sessions with Redis.
When enabling shared sessions, it results in an exception:
java.io.NotSerializableException: com.vaadin.flow.spring.scopes.BeanStore

Any hint why this happens?

#9189 doesn't seem to cover this issue.

`org.springframework.data.redis.serializer.SerializationException: Cannot serialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: com.vaadin.flow.spring.scopes.BeanStore
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:96) ~[spring-data-redis-2.0.9.RELEASE.jar:2.0.9.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.rawHashValue(AbstractOperations.java:184) ~[spring-data-redis-2.0.9.RELEASE.jar:2.0.9.RELEASE]
	at org.springframework.data.redis.core.DefaultHashOperations.putAll(DefaultHashOperations.java:133) ~[spring-data-redis-2.0.9.RELEASE.jar:2.0.9.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.putAll(DefaultBoundHashOperations.java:136) ~[spring-data-redis-2.0.9.RELEASE.jar:2.0.9.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.saveDelta(RedisOperationsSessionRepository.java:776) ~[spring-session-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository$RedisSession.access$000(RedisOperationsSessionRepository.java:649) ~[spring-session-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:384) ~[spring-session-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.save(RedisOperationsSessionRepository.java:245) ~[spring-session-data-redis-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:234) ~[spring-session-core-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:197) ~[spring-session-core-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:150) ~[spring-session-core-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:81) ~[spring-session-core-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:472) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) ~[tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:349) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:800) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1471) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.32.jar:8.5.32]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: com.vaadin.flow.spring.scopes.BeanStore
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:68) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:35) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.serialize(JdkSerializationRedisSerializer.java:94) ~[spring-data-redis-2.0.9.RELEASE.jar:2.0.9.RELEASE]
	... 33 common frames omitted
Caused by: java.io.NotSerializableException: com.vaadin.flow.spring.scopes.BeanStore
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1845) ~[na:na]
	at java.base/java.util.HashMap.writeObject(HashMap.java:1416) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at java.base/java.util.HashMap.internalWriteEntries(HashMap.java:1845) ~[na:na]
	at java.base/java.util.HashMap.writeObject(HashMap.java:1416) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at java.base/java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1130) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1497) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349) ~[na:na]
	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:63) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 35 common frames omitted`

**Comment by miclefebvre** [comment]
Can someone confirm if it's supported to have a replicated session in Kubernetes ?

I found this blog post: https://vaadin.com/blog/microservices-high-availability
and this thread: https://vaadin.com/forum/thread/17277282/17277283 showing errors with session.

**Comment by Legioth** [comment]
Any form of session replication is very difficult to support with Vaadin's server-side architecture because of the way it's based on having a consistent server-side representation of what is currently shown in the user's browser. This architecture is a trade-off between developer convenience and some other qualities.

A more appropriate solution for most situations is to use sticky sessions in the load balancer. See https://vaadin.com/blog/microservices-high-availability and https://vaadin.com/blog/session-replication-in-the-world-of-vaadin for more information.

Since the main purpose of Spring Session is to enable session replication, this also means that it's  very unlikely that we will add any support for it.

On the other hand, we are also investigating alternative ways of building applications without sacrificing end-to-end type safety and convenient access to backend services. You can read more about that initiative at https://vaadin.com/labs/vaadin-connect.

**Comment by sriharrsha** [comment]
Any update on vaadin-connect

**Comment by Legioth** [comment]
> Any update on vaadin-connect

What was known as Connect on year ago has been a part of Vaadin since version 15. It's nowadays know as [Vaadin Fusion](https://vaadin.com/blog/reintroducing-vaadin-flow-and-fusion).

Fusion uses the HTTP session only for keeping track of authentication and a CSRF token. This most likely very compatible with any typical session replication approach, but I haven't heard from anyone who would have tested it out in practice.

**Comment by sriharrsha** [comment]
So do you mean we can never achieve spring session support in Vaadin Flow project? If that's true is there any way to convert flow into fusion automatically?

Please fix this issue for Java World of Vaadin

**Comment by Legioth** [comment]
An architecture like Flow has benefits for e.g. security, developer productivity, and the convenience of doing everything in server-side Java. One of the sacrifices needed to get those benefits is that the HTTP session size is typically between 100 kb and 10 mb, which in turn makes session replication very impractical.

This is unfortunately a fundamental architectural tradeoff without any fix in sight.

**Comment by sriharrsha** [comment]
Is there any tutorial for sticky sessions instead of session replication on Vaadin Spring Boot for Google AppEngine. I added the session_affinity flag to true but it didn't work. The Vaadin App restarts continuously in an infinite loop due to automatic scaling.

**Comment by Legioth** [comment]
The way Google App Engine deals with sessions isn't a good fit with Vaadin if you want to scale beyond one instance. If you want to stick to Google's cloud offerings with a more complex deployment, then I'd recommend the Google Kubernetes Engine option described in https://vaadin.com/learn/tutorials/cloud-deployment/google.

Another alternative if you want to stick to the simplicity similar to GAE is to consider Heroku as an alternative. That approach is described in https://vaadin.com/learn/tutorials/cloud-deployment/heroku.

**Comment by Paulukr** [comment]
> 
> 
> An architecture like Flow has benefits for e.g. security, developer productivity, and the convenience of doing everything in server-side Java. One of the sacrifices needed to get those benefits is that the HTTP session size is typically between 100 kb and 10 mb, which in turn makes session replication very impractical.
> 
> This is unfortunately a fundamental architectural tradeoff without any fix in sight.

Why impractical? 10mb isn't much for internal network and in-memory database.

**Comment by Legioth** [comment]
The main reason for using session replication is to enable working at a larger scale than what a single server can support. At such scales, 10 mb _per request_ might lead to other bottlenecks.

That amount of data might or might not be a blocker depending on other circumstances, but it's surely 10000 times more impractical than the typical ~1 kb size that you'd get if the session only contains authentication information and not much more than that.

I can also mention the new-ish [Hazelcast tutorial](https://vaadin.com/learn/tutorials/hazelcast) that shows a relatively practical approach to session replication even though it's still also based on first having a load balancer with sticky sessions and then accepting the small risk of corruption because of the lack of distributed locking in cases when a session needs to move between nodes.
