### ISSUE TITLE
Using Spring Web Application in Vaadin Flow throw Exception in Oracle Weblogic

### ISSUE THREAD

**Issue by micsigen** [vaadin/spring#342]
Hi everybody,
following this [article](https://vaadin.com/docs/v10/flow/spring/tutorial-spring-basic-mvc.html) to set up Spring in my Weblogic application with the next code that is part of class that implements _WebApplicationInitializer_.

    @Override
    public void onStartup(ServletContext servletContext) {
        AnnotationConfigWebApplicationContext context = new AnnotationConfigWebApplicationContext();
        context.scan("...");
        servletContext.addListener(new ContextLoaderListener(context));

        ServletRegistration.Dynamic dispatcher = servletContext.addServlet("dispatcher", new SpringServlet(context));
        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping("/*");
    }

If I run this Web application on Oracle Weblogic 12.2.1 then I got the next error and the servlet cannot started. **With Jetty server working fine.**

> Aug 22, 2018 1:05:56 PM org.springframework.web.context.ContextLoader initWebApplicationContext
INFO: Root WebApplicationContext: initialization completed in 3763 ms
<Aug 22, 2018 1:05:56 PM GMT> <Error> <HTTP> <BEA-101216> <Servlet: "dispatcher" failed to preload on startup in Web application: "icbsfe-war-1.0-SNAPSHOT.war".
org.jboss.weld.exceptions.CreationException: WELD-001530: Cannot produce an instance of class com.vaadin.flow.spring.SpringServlet.
at org.jboss.weld.injection.producer.NonProducibleInjectionTarget.produce(NonProducibleInjectionTarget.java:55)
at com.oracle.injection.provider.weld.WeldBeanManager.newBeanInstance(WeldBeanManager.java:94)
at com.oracle.injection.integration.utils.InjectionBeanCreator.newBeanInstance(InjectionBeanCreator.java:127)
at weblogic.servlet.internal.InjectionBasedWebComponentCreator.createServletInstance(InjectionBasedWebComponentCreator.java:102)
at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.newServletInstanceIfNecessary(StubSecurityHelper.java:365)

Pieces of my pom.xml:
Vaadin core version: 10.0.2
Vaadin spring version: 10.0.0
Weblogic version: 12.2.1

Thanks in advice,
Balazs

**Comment by micsigen** [comment]
I found the solution that can be built into source.
The problem is when JBOSS Weld Core library try to inject SpringServlet then check if the injected class has No-args constructor and other condition. 
The validation is on https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/util/Beans.java class.

I created a class that extended from SpringServlet and I create a Non-args constructor that call constructor of super class.

```
public class WeblogicSpringServlet extends SpringServlet {

    public WeblogicSpringServlet() {
        this(ContextLoader.getCurrentWebApplicationContext());
    }

    public WeblogicSpringServlet(ApplicationContext context) {
        super(context);
    }
}
```
This servlet will be called on WebApplicationInitializer subclass.

```
public class ICBSWebAppInitializer implements WebApplicationInitializer {
    @Override
    public void onStartup(ServletContext servletContext) {
        AnnotationConfigWebApplicationContext context = new AnnotationConfigWebApplicationContext();
        ...
        servletContext.addListener(new ContextLoaderListener(context));
        ...
        ServletRegistration.Dynamic dispatcher = servletContext.addServlet("dispatcher", new WeblogicSpringServlet(context));
        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping("/*");
    }
}
```

**Comment by Legioth** [comment]
I would assume this is something that could be changed in the actual product so that WebLogic users wouldn't have to do workarounds?

**Comment by micsigen** [comment]
You are right if this issue is really exists and not wrong settings caused. 
Is it possible to test any simple application on Weblogic that is not Spring Boot based, but Vaadin 10 and use Spring?
