### ISSUE TITLE
There was an exception while trying to navigate to '' with the exception message 'Can't move a node from one state tree to another' java.lang.IllegalStateException: Can't move a node from one state tree to another

### ISSUE THREAD

**Issue by HoHo1979** [vaadin/spring#366]
I had a spring boot with Vaadin flow, (No static and singleton class, BroadCaster and Repository used with ApplicationScope, Vaadin: 10.0.5, spring-boot-starter-parent: 2.0.5.release) 

open http://localhost:8888 and then refresh, I got 
java.lang.IllegalStateException: Can't move a node from one state tree to another
	at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:474) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.StateNode.lambda$setTree$2(StateNode.java:266) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:433) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:266) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:198) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:78) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:53) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:42) ~[flow-server-1.0.5.jar:na]
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:92) ~[flow-server-1.0.5.jar:na]

code link, username: abc, password: 123
https://github.com/HoHo1979/Vaadin10FlowFarm

**Comment by Legioth** [comment]
SensorForm is session scoped, which means that the same instance would be used for all UIs in the same user session.

**Comment by HoHo1979** [comment]
> SensorForm is session scoped, which means that the same instance would be used for all UIs in the same user session.

Thanks, Legioth, I changed the SensorForm to UIscoped, the problem goes away.  

Can you please clarify?
According to the documentation of V10, It says " Each browser refresh will reload the UI."
If I understand this correctly when I press refresh, a new UI is generated by the server and the sensorForm with SessionScope cannot be injected into the UI? If it is across all UI under SessionScope, it shouldn't cause the problem, should it?

**Comment by Legioth** [comment]
A component instance can only have one parent at the same time. If a Vaadin component is session scoped, the same instance would have to be attached to each UI instance in that session, which cannot work.
