### ISSUE TITLE
Having @UIScope bean may cause unnecessary exception if application has Vaadin based ErrorView

### ISSUE THREAD

**Issue by TatuLund** [vaadin/spring#487]
Having @UIScope in initial route will cause an exception

Vaadin 13.0.12 with MPR

See the stack trace below

[http-nio-80-exec-2] ERROR com.vaadin.flow.router.InternalServerError - There was an exception while trying to navigate to ''
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'overviewImpl': Scope 'vaadin-ui' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: Current VaadinSession is not open
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:362)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:224)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1012)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:338)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333)
 at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
 at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:85)
 at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:158)
 at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:121)
 at java.util.Optional.orElseGet(Optional.java:267)
 at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:120)
 at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:178)
 at com.vaadin.flow.router.Router.handleNavigation(Router.java:223)
 at com.vaadin.flow.router.Router.navigate(Router.java:194)
 at com.vaadin.flow.router.Router.initializeUI(Router.java:92)
 at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1117)
 at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:396)
 at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
 at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
 at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
 at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:81)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
 at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
 at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:356)
 at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
 at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141)
 at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
 at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
 at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:873)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:858)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at xxx.application.doFilter(KOAuth2ClientAuthenticationProcessingFilter.java:292)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
 at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
 at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at xxx.applicatoon.LogbackContextFilter.doFilter(LogbackContextFilter.java:53)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at xxx.application.doFilter(KOAuth2ClientAuthenticationProcessingFilter.java:292)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
 at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
 at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
 at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
 at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
 at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
 at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:105)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:123)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
 at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:685)
 at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Current VaadinSession is not open
 at com.vaadin.flow.spring.scopes.AbstractScope.getVaadinSession(AbstractScope.java:79)
 at com.vaadin.flow.spring.scopes.VaadinUIScope.getBeanStore(VaadinUIScope.java:121)
 at com.vaadin.flow.spring.scopes.AbstractScope.get(AbstractScope.java:44)
 at com.vaadin.flow.spring.scopes.VaadinUIScope.get(VaadinUIScope.java:42)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:350)
 ... 134 more

**Comment by denis-anisimov** [comment]
The reason of the behavior is:

```
Caused by: java.lang.IllegalStateException: Current VaadinSession is not open
at com.vaadin.flow.spring.scopes.AbstractScope.getVaadinSession(AbstractScope.java:79)
at com.vaadin.flow.spring.scopes.VaadinUIScope.getBeanStore(VaadinUIScope.java:121)
at com.vaadin.flow.spring.scopes.AbstractScope.get(AbstractScope.java:44)
at com.vaadin.flow.spring.scopes.VaadinUIScope.get(VaadinUIScope.java:42)
```

For some reason the vaadin session state is not open.

`Having @uiscope in initial route will cause an exception`: I've checked that this is not a reason of the exception. Adding `@UIScope` to the `MainView` which is the initial (and only one route) in the `skeleton-starter-flow-spring` project doesn't break anything.

So please provide a project which I can use to reproduce it or steps to reproduce.

**Comment by brp-magnusd** [comment]
We are experiencing this very issue (and same exception) as well. Maybe it is related to #253? As a workaround we are delaying some initialization so it isn't performed in the initial request but scheduled and pushed to the UI immediately after. The same code then works without `Current VaadinSession is not open` being thrown...

**Comment by TatuLund** [comment]
I tried to debug this "Caused by: java.lang.IllegalStateException: Current VaadinSession is not open" exception. It seems to be somehow linked to Spring session fixation and is a corner case timing problem. We will get this exception if there is VaadinSession that is still alive and being killed by Spring session fixation and at the same time we are logging in and new VaadinSession is being created. Spring will throw this exception, since the the session being killed is closed and now UIScoped bean can be instantiated to that context. The application works since soon after this new VaadinSession is alive and UIScoped bean is instantiated with it.

**Comment by denis-anisimov** [comment]
Thanks for analysis but it's still worth to have exact steps to reproduce.

**Comment by TatuLund** [comment]
It looks like that is possible to have this problem when you have ErrorView created with Vaadin, which is being shown due some spurious request at the same time you are logging in the application. The VaadinSession that is not open is most likely the session related to error view, that is not open and being killed by session fixation.

**Comment by TatuLund** [comment]
In scope of our application it looks like that sufficient fix would be to change log level of this exception so that it is not shown in production.

**Comment by TatuLund** [comment]
This might be a duplicate of this one https://github.com/vaadin/spring/issues/78

**Comment by mehdi-vaadin** [comment]
@TatuLund having the steps to reproduce this issue would be helpful. Would you please add them here?

**Comment by TatuLund** [comment]
Here is a summary of known conditions:

- Make root layout @UIScoped
- Create ErrorView in Vaadin (we replaced ErrorView with JSP page in SpringBoot and after that problem disappeared)
- Use some application which has @PWA before deploying the test app in localhost. That will trigger the problem more often (in our production the problem was triggered by something else)
- CloseIdleSessions=true

**Comment by denis-anisimov** [comment]
>Create ErrorView in Vaadin (we replaced ErrorView with JSP page in SpringBoot and after that problem disappeared)

Please provide information what it the error view .
There is no such type.

It would be nice to have a project to reproduce the issue.
Without the exact steps to reproduce  no-one can say that the bug is fixed.

I may say for sure that I won't be able to reproduce the issue with this steps and then I won't be able to proceed and will ask again additional  info to reproduce the issue.

**Comment by TatuLund** [comment]
I was referring to Spring error view mechanism. We had the error view implemented as Vaadin UI. We got rid of the problem by replacing this Vaadin UI with jsp page with Spring's ErrorController.

**Comment by denis-anisimov** [comment]
It would be really nice to see an example how do you use this mechanism.

**Comment by AdrienC** [comment]
Hi,
We had this error with Spring Security's Session Fixation Protection. We were using the old strategy SessionFixationProtectionStrategy, and we no longer have the error since we use ChangeSessionIdAuthenticationStrategy (see [Spring Security Reference, Session Management](https://docs.spring.io/spring-security/site/docs/5.2.2.RELEASE/reference/htmlsingle/#ns-session-fixation)).

**Comment by denis-anisimov** [comment]
Closing this issue since there is no response for a long time with the exact steps to reproduce.
