### ISSUE TITLE
Sessions get destroyed after persistence context is closed

### ISSUE THREAD

**Issue by heruan** [vaadin/spring#511]
I'm using TestBench in `@SpringBootTest` integration tests and I have a `SessionDestroyListener` which uses a Spring `JpaRepository` to log session data: when the tests run they pass, but right after they passed this exception is thrown:

```
227490 [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.2 s - in it.axians.service.vaadin.incident.IncidentIntegrationTest

org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.IllegalStateException: EntityManagerFactory is closed
    at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)
    at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:376)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:572)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:360)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
    at it.axians.security.service.user.session.UserSessionService$$EnhancerBySpringCGLIB$$4595d23b.destroySession(<generated>)
    at it.axians.security.vaadin.user.session.UserSessionListener.sessionDestroy(UserSessionListener.java:130)
	at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:664)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:1983)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:648)
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1949)
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1916)
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:936)
	at com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:638)
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:178)
    ...
```

Which I guess is because the session destroy listeners are invoked after Spring has already closed the persistence context, i.e. the `EntityManagerFactory`.

**Comment by denis-anisimov** [comment]
So , I'm not sure where the issue is .....
Is it in the TestBench ?
Is it is Flow ?
Or is it in the custom app code ?
What I see from the stacktrace the last line which is not from Spring is `it.axians.security.service.user.session.UserSessionService$$EnhancerBySpringCGLIB$$4595d23b.destroySession`.
So it's somewhere inside a custom app class `UserSessionService`.
So may be this is just a bug inside the application ?

Otherwise I would like to see the code which causes the bug.

**Comment by heruan** [comment]
Thank you @denis-anisimov for the feedback! The `UserSessionService` is a Spring `@Service` which uses Spring repositories to persist session information; it does this registering its methods with `UserSessionListener`, which implements Vaadin's `SessionInitListener` and `SessionDestroyListener`.

The issue here is: when the Spring app initiates shutdown, implementations of Vaadin's `SessionDestroyListener` (such as my app's `UserSessionListener`) get their `sessionDestroy` event invoked after the Spring persistence context is closed, thus throwing that exception if the listeners try to access the persistence context (e.g. using repositories).

The code is very simple:

```java
public class UserSessionListener implements SessionInitListener, SessionDestroyListener {

    /* other methods */

    @Override
    public void sessionDestroy(SessionDestroyEvent event) {
        var id = event.getSession().getSession().getId();
       userSessionService.destroySession(id);
    }
}
```

During normal app execution all works fine, but when the app shuts down (e.g. after a TestBench test method in a `@SpringBootTest`) the servlet session is destroyed and listeners are invoked, but this happens after the persistence context is closed.

**Comment by denis-anisimov** [comment]
>The issue here is: when the Spring app initiates shutdown, implementations of Vaadin's SessionDestroyListener (such as my app's UserSessionListener) get their sessionDestroy event invoked after the Spring persistence context is closed, thus throwing that exception if the listeners try to access the persistence context 

So I'm trying to understand: is there any specific reason why session destroy event should be invoked before Spring persistence context is closed ?

Spring add-on doesn't have any code related to persistence context....
May be this is an issue is Spring ? Or something that should be just caught in the application code ?

**Comment by heruan** [comment]
> So I'm trying to understand: is there any specific reason why session destroy event should be invoked before Spring persistence context is closed ?

One reason is to let the listeners access the persistence layer.

> Spring add-on doesn't have any code related to persistence context....
May be this is an issue in Spring ?

I'm aware the add-on doesn't relate to persistence, but maybe there's a way to anticipate session destruction or provide an API to do that.

> Or something that should be just caught in the application code ?

This would mean data loss on app shutdown/restart.

**Comment by denis-anisimov** [comment]
I still would like to understand the issue within Vaadin.....
The persistence layer is closed by Spring.
The session is closed by Spring.
So Vaadin here is just a layer in session closing. So at the first glance I would say this is Spring issue.

I see only one possibility where Vaadin may be involved as something which introduce an issue:
`VaadinSession` is not closed right away with Http Session.
That may be an issue but I'm not sure whether this is a bug.

Could you try to use `HttpSessionBindingListener` and implement `valueUnbound` method to listen for the `HttpSessionBindingEvent`  and check whether the persistence context is still available ?
This is what `VaadinSession` does .

Another way could be `HttpSessionListener` to be notified about Http session destruction.

If you have persistence context available in those cases then you may use them instead VaadinSession destroy which has some additional logic on the top of http session destroy.

If persistence context is not available in those listeners then I don't see what we can do: it's Spring who closes the session and persistence in the way which you don't expect.

**Comment by heruan** [comment]
Thank you @denis-anisimov for the hints! In the meanwhile, I was trying to see what happens without involving the persistence context at all and I still get an exception:

```
java.lang.AssertionError: null
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1471) ~[flow-server-2.0.17.jar:2.0.17]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1554) ~[flow-server-2.0.17.jar:2.0.17]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246) ~[flow-server-2.0.17.jar:2.0.17]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:95) ~[vaadin-spring-12.0.6.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
```

I'm not sure if this is related, but there are no application classes involved this time. Seems like Vaadin's not coming along with `@SpringBootTest` 😕

**Comment by denis-anisimov** [comment]
Well, that looks like a different pure Vaadin issue .
Could you please create a ticket for this with the exact steps to reproduce ?
Thanks.

**Comment by heruan** [comment]
Thank you @denis-anisimov for explaining how Vaadin handles this and pointing me out to `HttpSessionListener`! Indeed the issue exists outside of Vaadin, so I'm going to close this and ask Spring 😉
