### ISSUE TITLE
Project does not compile with Java 16

### ISSUE THREAD

**Issue by Artur-** [vaadin/spring#751]
```
mvn install
```

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.vaadin.flow.spring.VaadinServletContextInitializerTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 3.045 sec <<< FAILURE!
errorParameterServletContextListenerEvent_hasCustomRouteNotFoundViewExtendingRouteNotFoundError_customRouteNotFoundViewIsRegistered(com.vaadin.flow.spring.VaadinServletContextInitializerTest)  Time elapsed: 2.29 sec  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @11739fa6
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.powermock.reflect.internal.WhiteboxImpl.doGetAllMethods(WhiteboxImpl.java:1508)
	at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1482)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1750)
	at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1789)
	at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:1008)
	at org.powermock.core.MockInvocation.findMethodToInvoke(MockInvocation.java:58)
	at org.powermock.core.MockInvocation.init(MockInvocation.java:35)
	at org.powermock.core.MockInvocation.<init>(MockInvocation.java:22)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:155)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:138)
	at com.vaadin.flow.spring.VaadinServletContextInitializerTest.init(VaadinServletContextInitializerTest.java)
```

**Comment by Artur-** [comment]
This prevents upgrading to Spring Boot 3
