### ISSUE TITLE
Mandatory url parameters break navigation

### ISSUE THREAD

**Issue by TatuLund** [vaadin/spring#864]
If you add mandatory parameter in url template, navigation breaks. 

**Steps to reproduce**

Create test application using start.vaadin.com, add multiple views to it. Change `AboutView `to be as below.

Observed behavior: None of the routes work

Expected behavior: See the text including the given parameter on screen

If you change `@Route(value = "about/:param", layout = MainView.class)` to `@Route(value = "about/:param?", layout = MainView.class)` or `@Route(value = "about/:param*", layout = MainView.class)`, then navigation works.

This bug does not occur if your application does not use Spring Boot.

Tested with Vaadin 14.6.7 and Vaadin 20

```
@Route(value = "about/:param", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements BeforeEnterObserver {

    private String param = "";
    private Span oppinions;

    public AboutView() {
        oppinions = new Span();
        add(oppinions);
    }
    
    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        param = event.getRouteParameters().get("param").orElse("");
        oppinions.setText("Todays opinnions for: "+param);
    }
}
```

Also if to fix the above by implementing `HasUrlParameter` instead, it still breaks in similar fashion

```
@Route(value = "about", layout = MainView.class)
@PageTitle("About")
@CssImport("./views/about/about-view.css")
public class AboutView extends Div implements HasUrlParameter<String> {

    private String param = "";
    private Span oppinions;

    public AboutView() {
        oppinions = new Span();
        add(oppinions);
    }
    
    @Override
    public void setParameter(BeforeEvent event, String parameter) {
        oppinions.setText("Todays opinnions for: "+parameter);        
    }
}
```

When you `@OptionalParameter` to `setParameter `application works.

**Comment by denis-anisimov** [comment]
I don't understand how it may work without Spring .
Also I don't see any `MainView` class. There is the `MainLayout` class.

The reason is the unsupported parameter in the _Application itself_.

```
com.vaadin.flow.router.NotFoundException: No route found for the given navigation target and parameters!
	at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:512)
	at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:228)
	at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:191)
	at com.vaadin.flow.router.RouterLink.setRoute(RouterLink.java:239)
	at com.example.application.views.MainLayout.createTab(MainLayout.java:147)
	at com.example.application.views.MainLayout.createMenuItems(MainLayout.java:138)
	at com.example.application.views.MainLayout.createMenu(MainLayout.java:120)
	at com.example.application.views.MainLayout.<init>(MainLayout.java:73)
```


This exception happens regardless whether this is a Spring application or not.
So it's expected that application is brtoken.
The unexpected thing is : there is no exception reported anywhere.

The application is based on `AppLayout` and I don't have any knowledge of this component.
So I cannot say whether this is something because of the `AppLayout`  or it's a generic issue in Flow that it doesn't report the exception in some case.
Anyway if the issue is the absence of the exception reporting (which I agree as an issue) then please localize it (make a simple project, don't use extra irrelevant `AppLayout`) and report it in Flow repository.

If I misunderstood something then please reopen issue or let me know I will reopen it.

**Comment by apgsga-stb** [comment]
Wait a minute... If I annotate a component with @Route(value = "ui/kunde-bearbeiten/:kundeid",...), I expect navigation to that component, if I enter http://localhost:8080/ui/kunde-bearbeiten/2. But it does not. The browser writes "Could not navigate to 'ui/kunde-bearbeiten/2' Reason: No route found for the given navigation target and parameters!"  What do you mean with "The reason is the unsupported parameter in the Application itself"?.  Where else, if not in the @Route annotation do I have to configure that parameter? And no, the issue is not the absence of the Exception, it's the not-working-of-route-parameters.

Yes, please reopen the issue.

**Comment by apgsga-stb** [comment]
By the way: `RouteConfiguration.forSessionScope().getUrl(viewClass, routeParameters)` leads to an exception too, if I apply it to that given component.

**Comment by TatuLund** [comment]
@denis-anisimov , instead of closing if you are sure that this is not Spring specific, the correct action is to move the ticket to Flow repo.
