### ISSUE TITLE
Spring 18/19 SNAPSHOT is broken

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/spring#865]
https://bender.vaadin.com/viewLog.html?buildId=246630&tab=buildResultsDiv&buildTypeId=Flow_Flow80_AddOns_Spring180Snapshot
https://bender.vaadin.com/viewLog.html?buildId=246687&tab=buildResultsDiv&buildTypeId=Flow_Flow90_AddOns_Spring190Snapshot

Failing tests are : 

FusionFormIT.no_validation_error_when_clearing_number_field
FusionFormIT.save_backend_loaded_empty_values_for_required_fields_no_runtime_errors
FusionFormIT.save_empty_values_for_required_fields_no_runtime_errors

SecurityIT.navigate_to_admin_view_prevented
SecurityIT.navigate_to_private_view_prevented

One of the exceptions:
```
java.lang.RuntimeException: no_validation_error_when_clearing_number_field[ANY_Chrome_](com.vaadin.flow.spring.fusionform.FusionFormIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:78)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at com.vaadin.testbench.parallel.ParallelScheduler$1.call(ParallelScheduler.java:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.junit.internal.runners.model.MultipleFailureException: There were 2 errors:
  org.openqa.selenium.TimeoutException(Expected condition failed: waiting for com.vaadin.flow.spring.fusionform.FusionFormIT$$Lambda$676/723643542@4a74c501 (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-184.eu-west-1.compute.internal', ip: '172.16.1.184', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: com.vaadin.testbench.TestBenchDriverProxy_$$_jvst91e_0
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 91.0.4472.114, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: /tmp/.com.google.Chrome.xB24Wu}, goog:chromeOptions: {debuggerAddress: localhost:41885}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 7a4559ece699d7caaa5d942410e...}
Session ID: 7a4559ece699d7caaa5d942410ef58a7)
  java.lang.AssertionError(Received error message in browser log console right after opening the page, message: [2021-08-03T07:03:58+0000] [SEVERE] http://172.16.1.184:9999/VAADIN/build/vaadin-3-6339d457e48bedb94710.cache.js 3952:521 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegist…ist-box" has already been used with this registry)
	at org.junit.runners.model.MultipleFailureException.assertEmpty(MultipleFailureException.java:102)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:39)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:68)
	... 11 more
------- Stdout: -------
07:04:09.009 [pool-1-thread-16] WARN com.vaadin.flow.testutil.TestBenchHelpers - This message in browser log console may be a potential error: '[2021-08-03T07:03:58+0000] [WARNING] http://172.16.1.184:9999/VAADIN/build/vaadin-bundle-fbc25a0885908045548f.cache.js 139:8 "The main 'lit-element' module entrypoint is deprecated. Please update your imports to use the 'lit' package: 'lit' and 'lit/decorators.ts' or import from 'lit-element/lit-element.ts'."'
```

**Comment by denis-anisimov** [comment]
The screenshots are empty.
The problem is apparently on the initial client side load which can be seen from the exception report.

**Comment by denis-anisimov** [comment]
Both SNAPSHOTS 18 and 19 again are broken because of the same tests:
https://bender.vaadin.com/viewLog.html?buildId=249256&tab=buildResultsDiv&buildTypeId=Flow_Flow90_AddOns_Spring190Snapshot
https://bender.vaadin.com/viewLog.html?buildId=249257&tab=buildResultsDiv&buildTypeId=Flow_Flow80_AddOns_Spring180Snapshot
